services:
  processor-rest:
    build: ./processor_rest
    container_name: processor-rest
    ports:
      - "8001:8000"

  gateway-rest:
    build: ./gateway_rest
    container_name: gateway-rest
    environment:
      - PROCESSOR_URL=http://processor-rest:8000
    depends_on:
      - processor-rest
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - gateway-rest
      - processor-rest
