global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "gateway-rest"
    metrics_path: /metrics
    static_configs:
      - targets: ["gateway-rest:8000"]

  - job_name: "processor-rest"
    metrics_path: /metrics
    static_configs:
      - targets: ["processor-rest:8000"]
